# Generated by Django 5.1.7 on 2025-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
