# Generated by Django 5.1.7 on 2025-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_stock_quantity_product_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
