# Generated by Django 5.1.7 on 2025-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deletd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
