# Generated by Django 5.1.7 on 2025-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_is_deletd_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_deletd',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
