# Generated by Django 5.1.7 on 2025-09-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
